import {
  AlertTriangle,
  CheckCircle2,
  FileSearch,
  LockKeyhole,
  Scale,
  ShieldCheck,
} from "lucide-react";

const TRUST_POINTS = [
  {
    icon: <Scale className="h-5 w-5" />,
    title: "Rule-Based Score",
    description:
      "The final numeric score is calculated by deterministic code, not randomly generated by the LLM.",
  },
  {
    icon: <FileSearch className="h-5 w-5" />,
    title: "Source Visibility",
    description:
      "Every report shows financial source, news source, memo provider, fallbacks, and warnings.",
  },
  {
    icon: <AlertTriangle className="h-5 w-5" />,
    title: "Missing Data Handling",
    description:
      "Unavailable financial fields are treated as unknown instead of being assumed positive or negative.",
  },
  {
    icon: <LockKeyhole className="h-5 w-5" />,
    title: "Local History",
    description:
      "Saved research history is stored in the browser using localStorage. No database is required for the demo.",
  },
];

const CHECKS = [
  "Agent execution trace included",
  "Fallback usage disclosed",
  "Investment disclaimer visible",
  "Exported memo includes warnings",
  "Comparison winner is deterministic",
  "Data quality is shown to reviewers",
];

export function TrustSection() {
  return (
    <section className="py-20">
      <div className="overflow-hidden rounded-[2.5rem] border border-slate-200 bg-white shadow-2xl shadow-slate-900/10 dark:border-white/10 dark:bg-white/[0.04] dark:shadow-black/30">
        <div className="grid lg:grid-cols-[0.9fr_1.1fr]">
          <div className="relative bg-slate-950 p-8 text-white md:p-10">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.25),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(139,92,246,0.22),_transparent_35%)]" />

            <div className="relative">
              <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-3xl border border-white/10 bg-white/10">
                <ShieldCheck className="h-8 w-8 text-emerald-300" />
              </div>

              <p className="mb-3 text-sm font-black uppercase tracking-[0.3em] text-emerald-300">
                Trust Layer
              </p>

              <h2 className="text-4xl font-black tracking-tight">
                Built to be inspected, not blindly trusted
              </h2>

              <p className="mt-5 text-base leading-7 text-slate-300">
                A serious AI research product should not hide how it reached a
                conclusion. EquityLens exposes its scoring model, data sources,
                fallbacks, warnings, and execution trace.
              </p>

              <div className="mt-8 grid gap-3">
                {CHECKS.map((check) => (
                  <div
                    key={check}
                    className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 px-4 py-3"
                  >
                    <CheckCircle2 className="h-5 w-5 text-emerald-300" />
                    <span className="text-sm font-semibold text-slate-200">
                      {check}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="p-8 md:p-10">
            <div className="mb-8">
              <p className="mb-3 text-sm font-black uppercase tracking-[0.3em] text-cyan-500">
                Transparency System
              </p>

              <h3 className="text-3xl font-black text-slate-950 dark:text-white">
                Every recommendation carries context
              </h3>

              <p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-400">
                The goal is not to make a magical black-box prediction. The goal
                is to create a repeatable research workflow that a reviewer can
                understand and verify.
              </p>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              {TRUST_POINTS.map((point) => (
                <div
                  key={point.title}
                  className="rounded-[1.5rem] border border-slate-200 bg-slate-50 p-5 dark:border-white/10 dark:bg-slate-950/60"
                >
                  <div className="mb-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-cyan-600 shadow-sm dark:bg-white/10 dark:text-cyan-300">
                    {point.icon}
                  </div>

                  <h4 className="font-black text-slate-950 dark:text-white">
                    {point.title}
                  </h4>

                  <p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">
                    {point.description}
                  </p>
                </div>
              ))}
            </div>

            <div className="mt-6 rounded-[1.5rem] border border-amber-400/20 bg-amber-400/10 p-5">
              <div className="mb-2 flex items-center gap-2 text-amber-600 dark:text-amber-300">
                <AlertTriangle className="h-5 w-5" />
                <p className="font-black">Important disclaimer</p>
              </div>

              <p className="text-sm leading-6 text-slate-700 dark:text-slate-300">
                EquityLens AI is for educational and research demonstration
                only. It is not financial advice. Real investment decisions
                require independent verification and professional judgment.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}